service: s3-document-api

frameworkVersion: '2'

provider:
  name: 'aws'
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:getObject
      Resource: arn:aws:s3:::${self:custom.appName}/*


custom:
  appName: ${opt:stage, 'dev'}-s3-document-api
  
resources:
  Resources:
    DocumentBucket:
      Type: AWS::S3::Bucket
      Properties:
          BucketName: ${self:custom.appName}
          AccessControl: Private
          CorsConfiguration:
            CorsRules:
            - AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
              AllowedOrigins:
              - "*"
              AllowedHeaders:
              - "*"

functions:
  writeDocument:
    name: ${self:custom.appName}-write-document 
    handler: document-writer/handler.run 
    events:
      - httpApi:
          path: /document
          method: post   
    environment:
      BUCKET_NAME: ${self:custom.appName}
  readDocument:
    name: ${self:custom.appName}-read-document 
    handler: document-reader/handler.run 
    events:
      - httpApi:
          path: /document/{key}
          method: get   
    environment:
      BUCKET_NAME: ${self:custom.appName}
